### ISSUE TITLE
game getting stuck if there are no playable spaces for the current player

### ISSUE THREAD

**Issue by Asutosh989** [Rishav159/othello#1]
Screenshot:
<img width="856" alt="Screenshot 2023-12-15 at 12 16 58 AM" src="https://github.com/Rishav159/othello/assets/17357530/50aade1c-bcac-484f-9e91-13b2c8fd617a">

Expected Behaviour:
Turn should pass on the other player

**Comment by Rishav159** [comment]
This is fixed
