### ISSUE TITLE
Show a hover effect when a player hovers over a empty area

### ISSUE THREAD

**Issue by Rishav159** [Rishav159/othello#5]
Just temporarily show the cell as filled with opacity 70%. This will help users visualize where they are going to put the token and for which color.

**Comment by Asutosh989** [comment]
Implemented with 50% opacity. Looks better.
<img width="1115" alt="Screenshot 2023-12-15 at 5 33 35 AM" src="https://github.com/Rishav159/othello/assets/17357530/1a8a3ba4-f1b9-46fa-b677-d28203650cac">
